environment = "dev"
project = "lab-proj-01"
zone = "us-west1-b"
region = "us-west1"
gcp_auth_file = "/tmp/sa_key.json"
gcp_token_file = "/tmp/access_token.txt"
bucket_name = "tf_state_folder"
prefix = "tf-state/network"

vpc_name = "lab-vpc"
