environment = "dev"
project = "lab-proj-02"
# zone = "us-west1-b"
region = "us-west1"

gcp_auth_file = "/tmp/sa_key.json"
gcp_token_file = "/tmp/access_token.txt"
bucket_name = "tf_state_folder"
storage_class = "REGIONAL"
# storage_class = "MULTI_REGIONAL"
